nav:
  - Home: 'iceland-ml/README.md'
  - Lab Summary: 'iceland-ml/LAB_SUMMARY.md'
  - Labs:
    - Lab 1 - Judoor & HPC Access: 'units/lab1/README.md'
    - Lab 2 - Jupyter-JSC & Git: 'units/lab2/README.md'
    - Lab 3 - Sentinel-2 Acquisition: 'units/lab3/README.md'
    - Lab 4 - Data Preprocessing: 'units/lab4/README.md'
    - Lab 5 - Patch Extraction: 'units/lab5/README.md'
    - Lab 6 - Baseline Model Training: 'units/lab6/README.md'
    - Lab 7 - Model Evaluation: 'units/lab7/README.md'
    - Lab 8 - TerraTorch Fine-tuning: 'units/lab8/README.md'

# Project information
site_name: TÃ–V606M - Machine Learning for Earth Observation

# Configuration
theme:
  name: material
  palette:
    scheme: iceland
  font:
    text: Source Sans 3
    code: DM Mono
  logo: assets/computer.png
  favicon: assets/computer.png
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
